flowchart TD
  T2 --- T1 --- T3
  B2 --- B1 --- B3

  T1 --- B1

  T2 --- T4 --- T5 --- T3
  B2 --- B4 --- B5 --- B3

  subgraph top
    T1
    T2
    T3
    T4
    T5
  end

  subgraph down
    B1
    B2
    B3
    B4
    B5
  end